version: "3.7"

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:10
    env_file:
        - ./.env.docker
    volumes:
      - flask-app-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
        - ./.env.docker
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: "sh /app/docker_script.sh"

volumes:
  flask-app-db:
    name: flask-app-db
